// <auto-generated />
using System;
using CafeEmpApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeEmpApi.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230521011731_APIMigration")]
    partial class APIMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("CafeEmpApi.Data.Cafe", b =>
                {
                    b.Property<int>("CafeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CafeId");

                    b.ToTable("Cafes");

                    b.HasData(
                        new
                        {
                            CafeId = 1,
                            Description = "Cafe Desc 1",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            Location = "Cafe Location 1",
                            Name = "Cafe Name 1"
                        },
                        new
                        {
                            CafeId = 2,
                            Description = "Cafe Desc 2",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            Location = "Cafe Location 2",
                            Name = "Cafe Name 2"
                        },
                        new
                        {
                            CafeId = 3,
                            Description = "Cafe Desc 3",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            Location = "Cafe Location 3",
                            Name = "Cafe Name 3"
                        },
                        new
                        {
                            CafeId = 4,
                            Description = "Cafe Desc 4",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            Location = "Cafe Location 4",
                            Name = "Cafe Name 4"
                        },
                        new
                        {
                            CafeId = 5,
                            Description = "Cafe Desc 5",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            Location = "Cafe Location 5",
                            Name = "Cafe Name 5"
                        },
                        new
                        {
                            CafeId = 6,
                            Description = "Cafe Desc 6",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            Location = "Cafe Location 6",
                            Name = "Cafe Name 6"
                        });
                });

            modelBuilder.Entity("CafeEmpApi.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email_address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone_number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email_address = "Emp Email 1",
                            Gender = "Gender 1",
                            Name = "Emp Name 1",
                            Phone_number = "Emp Phone 1"
                        },
                        new
                        {
                            Id = 2,
                            Email_address = "Emp Email 2",
                            Gender = "Gender 2",
                            Name = "Emp Name 2",
                            Phone_number = "Emp Phone 2"
                        },
                        new
                        {
                            Id = 3,
                            Email_address = "Emp Email 3",
                            Gender = "Gender 3",
                            Name = "Emp Name 3",
                            Phone_number = "Emp Phone 3"
                        },
                        new
                        {
                            Id = 4,
                            Email_address = "Emp Email 4",
                            Gender = "Gender 4",
                            Name = "Emp Name 4",
                            Phone_number = "Emp Phone 4"
                        },
                        new
                        {
                            Id = 5,
                            Email_address = "Emp Email 5",
                            Gender = "Gender 5",
                            Name = "Emp Name 5",
                            Phone_number = "Emp Phone 5"
                        },
                        new
                        {
                            Id = 6,
                            Email_address = "Emp Email 6",
                            Gender = "Gender 6",
                            Name = "Emp Name 6",
                            Phone_number = "Emp Phone 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
